--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MegaHostings-Development-PocketMine/SimpleHub
build-by-default: true
branches:
- main
projects:
  HubSystem:
    path: HubSystem/
...
